### ISSUE TITLE
Add a composer.json?

### ISSUE THREAD

**Issue by royduin** [wp-premium/advanced-custom-fields-pro#1]
It would be nice if there was a `composer.json` file:
```
{
	"name": "wp-premium/advanced-custom-fields-pro",
	"type": "wordpress-plugin"
}
```
Not only for this repo, but for all the wp-premium repo's. What do you think @remcotolsma or @elliotcondon?

**Comment by elliotcondon** [comment]
@royduin you're joking, right? This is not an official repo. You should not support pirates like wp-premium.

**Comment by royduin** [comment]
Hereby @elliotcondon his reaction which was probably removed:
```
@royduin you're joking, right? This is not an official repo. You should not support pirates like wp-premium.
```
I saw @elliotcondon his name in the commit list here: https://github.com/wp-premium/advanced-custom-fields-pro/commits/master so I thought it was ok. If it's not allowed, do something about it @elliotcondon? I'm closing this issue and going to use my own private repo with a `composer.json`.
