### ISSUE TITLE
Please provide a ACF Addons

### ISSUE THREAD

**Issue by rvpatel** [wp-premium/advanced-custom-fields-pro#3]
Thanks for share a plugin.
Please share this add-ons.
https://www.advancedcustomfields.com/add-ons/

**Comment by remcotolsma** [comment]
> Advanced Custom Fields Pro, Git-ified. Synced manual! This repository is just a mirror of the Advanced Custom Fields Pro plugin. Please do not send pull requests and issues.

https://github.com/wp-premium/advanced-custom-fields-pro
