### ISSUE TITLE
$form.find(...).exists is not a function

### ISSUE THREAD

**Issue by kirillrocks** [wp-premium/advanced-custom-fields-pro#4]
$form.find(...).exists is not a function - getting this error on widgets.php

```
// bail early if this form does not contain ACF data
		if( !$form.find('#acf-form-data').exists() ) {
		
			return true;
		
		}
```

**Comment by remcotolsma** [comment]
> Advanced Custom Fields Pro, Git-ified. Synced manual! This repository is just a mirror of the Advanced Custom Fields Pro plugin. **Please do not send pull requests and issues.**

https://github.com/wp-premium/advanced-custom-fields-pro
